version: "3.0"

services:
  api:
    container_name: "poc-daiwa"
    build: .
    environment:
      PYTHONPATH: /workspace/app
    working_dir: /workspace
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/workspace/app
      - ./.devcontainer:/workspace/.devcontainer
      - ./scripts:/workspace/scripts
